### ISSUE TITLE
Switch front end dependency management from Bower to Browserify+Babel

### ISSUE THREAD

**Issue by Anirudh94** [Anirudh94/boreas#17]
Many dependencies prefer/need commonjs style `require()` statements to use their api. To better accommodate we should switch from Bower to using Browserify to compile code for front end use. Babel is needed as an intermediate step to convert any jsx code for use by Browserify.

We can also easily automate this with a taskrunner like Gulp/Grunt

**Comment by andrewazores** [comment]
This is partially done - browserify/babel are in use, but bower hasn't been removed.

**Comment by andrewazores** [comment]
Bower has been removed. Automation is still just a one-liner script run by npm - probably not ideal.
